### ISSUE TITLE
Convert from JSON to EMMessage

### ISSUE THREAD

**Issue by skensell** [HyphenateInc/Hyphenate-SDK-iOS#7]
I am planning on permanently storing messages and chat history on my server. To restore chat history for someone on the iOS client, it seems I will need to call `importMessages:completion:` on the `chatManager` which takes an array of `EMMessage`s.  My problem is that you have not made public any converter from the raw message JSON to an `EMMessage`.  Parsing the different types of messages and setting the appropriate properties of an `EMMessage` (and also for importing `EMConversation`s) would be quite tedious and prone to errors on API upgrades.  Could you make a publicly accessible converter?

Or am I misunderstanding something about the suggested way of restoring chat history?

**Comment by jerrywu12** [comment]
forwarded to SDK team. stay tuned!
